version: '3.4'

services:
  api:
    image: ghav95.com/api/test
    container_name: myapp-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080"
      - "8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-2022
    environment:
      SA_PASSWORD: "Nexer2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"