version: '3.4'

services:
  api:
    image: api:dev
    container_name: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Nexer2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
